### ISSUE TITLE
Use new version management syntax [library catalog syntax]

### ISSUE THREAD

**Issue by SamuelMarks** [supabase-community/supabase-kt#762]
For example, what I have:

### composeApp/build.gradle.kts
```js
// kotlin.sourceSets.commonMain.dependencies
implementation(libs.bom)
implementation(libs.postgrest_kt)
implementation(libs.auth_kt)
implementation(libs.realtime_kt)
```

### gradle/libs.versions.toml
```toml
[versions]
supabase-kt = "3.0.1"

[libraries]
auth-kt = { module = "io.github.jan-tennert.supabase:auth-kt", version.ref = "supabase-kt" }
postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "supabase-kt" }
realtime-kt = { module = "io.github.jan-tennert.supabase:realtime-kt", version.ref = "supabase-kt" }
bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabase-kt" }
```
